export const countryCodes = [
    { id: 1, name: 'Afghanistan', code: '+93', svg: 'https://flagcdn.com/af.svg' },
    { id: 2, name: 'Albania', code: '+355', svg: 'https://flagcdn.com/al.svg' },
    { id: 3, name: 'Algeria', code: '+213', svg: 'https://flagcdn.com/dz.svg' },
    { id: 4, name: 'Andorra', code: '+376', svg: 'https://flagcdn.com/ad.svg' },
    { id: 5, name: 'Angola', code: '+244', svg: 'https://flagcdn.com/ao.svg' },
    { id: 6, name: 'Argentina', code: '+54', svg: 'https://flagcdn.com/ar.svg' },
    { id: 7, name: 'Armenia', code: '+374', svg: 'https://flagcdn.com/am.svg' },
    { id: 8, name: 'Australia', code: '+61', svg: 'https://flagcdn.com/au.svg' },
    { id: 9, name: 'Austria', code: '+43', svg: 'https://flagcdn.com/at.svg' },
    { id: 10, name: 'Azerbaijan', code: '+994', svg: 'https://flagcdn.com/az.svg' },
    { id: 11, name: 'Bahamas', code: '+1-242', svg: 'https://flagcdn.com/bs.svg' },
    { id: 12, name: 'Bahrain', code: '+973', svg: 'https://flagcdn.com/bh.svg' },
    { id: 13, name: 'Bangladesh', code: '+880', svg: 'https://flagcdn.com/bd.svg' },
    { id: 14, name: 'Barbados', code: '+1-246', svg: 'https://flagcdn.com/bb.svg' },
    { id: 15, name: 'Belarus', code: '+375', svg: 'https://flagcdn.com/by.svg' },
    { id: 16, name: 'Belgium', code: '+32', svg: 'https://flagcdn.com/be.svg' },
    { id: 17, name: 'Belize', code: '+501', svg: 'https://flagcdn.com/bz.svg' },
    { id: 18, name: 'Benin', code: '+229', svg: 'https://flagcdn.com/bj.svg' },
    { id: 19, name: 'Bhutan', code: '+975', svg: 'https://flagcdn.com/bt.svg' },
    { id: 20, name: 'Bolivia', code: '+591', svg: 'https://flagcdn.com/bo.svg' },
    { id: 21, name: 'Bosnia and Herzegovina', code: '+387', svg: 'https://flagcdn.com/ba.svg' },
    { id: 22, name: 'Botswana', code: '+267', svg: 'https://flagcdn.com/bw.svg' },
    { id: 23, name: 'Brazil', code: '+55', svg: 'https://flagcdn.com/br.svg' },
    { id: 24, name: 'Brunei', code: '+673', svg: 'https://flagcdn.com/bn.svg' },
    { id: 25, name: 'Bulgaria', code: '+359', svg: 'https://flagcdn.com/bg.svg' },
    { id: 26, name: 'Burkina Faso', code: '+226', svg: 'https://flagcdn.com/bf.svg' },
    { id: 27, name: 'Burundi', code: '+257', svg: 'https://flagcdn.com/bi.svg' },
    { id: 28, name: 'Cabo Verde', code: '+238', svg: 'https://flagcdn.com/cv.svg' },
    { id: 29, name: 'Cambodia', code: '+855', svg: 'https://flagcdn.com/kh.svg' },
    { id: 30, name: 'Cameroon', code: '+237', svg: 'https://flagcdn.com/cm.svg' },
    { id: 31, name: 'Canada', code: '+1', svg: 'https://flagcdn.com/ca.svg' },
    { id: 32, name: 'Central African Republic', code: '+236', svg: 'https://flagcdn.com/cf.svg' },
    { id: 33, name: 'Chad', code: '+235', svg: 'https://flagcdn.com/td.svg' },
    { id: 34, name: 'Chile', code: '+56', svg: 'https://flagcdn.com/cl.svg' },
    { id: 35, name: 'China', code: '+86', svg: 'https://flagcdn.com/cn.svg' },
    { id: 36, name: 'Colombia', code: '+57', svg: 'https://flagcdn.com/co.svg' },
    { id: 37, name: 'Comoros', code: '+269', svg: 'https://flagcdn.com/km.svg' },
    { id: 38, name: 'Congo', code: '+242', svg: 'https://flagcdn.com/cg.svg' },
    { id: 39, name: 'Congo, Democratic Republic of the', code: '+243', svg: 'https://flagcdn.com/drc.svg' },
    { id: 40, name: 'Costa Rica', code: '+506', svg: 'https://flagcdn.com/cr.svg' },
    { id: 41, name: 'Croatia', code: '+385', svg: 'https://flagcdn.com/hr.svg' },
    { id: 42, name: 'Cuba', code: '+53', svg: 'https://flagcdn.com/cu.svg' },
    { id: 43, name: 'Cyprus', code: '+357', svg: 'https://flagcdn.com/cy.svg' },
    { id: 44, name: 'Czech Republic', code: '+420', svg: 'https://flagcdn.com/cz.svg' },
    { id: 45, name: 'Denmark', code: '+45', svg: 'https://flagcdn.com/dk.svg' },
    { id: 46, name: 'Djibouti', code: '+253', svg: 'https://flagcdn.com/dj.svg' },
    { id: 47, name: 'Dominica', code: '+1-767', svg: 'https://flagcdn.com/dm.svg' },
    { id: 48, name: 'Dominican Republic', code: '+1-809', svg: 'https://flagcdn.com/do.svg' },
    { id: 49, name: 'Ecuador', code: '+593', svg: 'https://flagcdn.com/ec.svg' },
    { id: 50, name: 'Egypt', code: '+20', svg: 'https://flagcdn.com/eg.svg' },
    { id: 51, name: 'El Salvador', code: '+503', svg: 'https://flagcdn.com/sv.svg' },
    { id: 52, name: 'Equatorial Guinea', code: '+240', svg: 'https://flagcdn.com/gq.svg' },
    { id: 53, name: 'Eritrea', code: '+291', svg: 'https://flagcdn.com/er.svg' },
    { id: 54, name: 'Estonia', code: '+372', svg: 'https://flagcdn.com/ee.svg' },
    { id: 55, name: 'Eswatini', code: '+268', svg: 'https://flagcdn.com/sz.svg' },
    { id: 56, name: 'Ethiopia', code: '+251', svg: 'https://flagcdn.com/et.svg' },
    { id: 57, name: 'Fiji', code: '+679', svg: 'https://flagcdn.com/fj.svg' },
    { id: 58, name: 'Finland', code: '+358', svg: 'https://flagcdn.com/fi.svg' },
    { id: 59, name: 'France', code: '+33', svg: 'https://flagcdn.com/fr.svg' },
    { id: 60, name: 'Gabon', code: '+241', svg: 'https://flagcdn.com/ga.svg' },
    { id: 61, name: 'Gambia', code: '+220', svg: 'https://flagcdn.com/gb.svg' },
    { id: 62, name: 'Georgia', code: '+995', svg: 'https://flagcdn.com/ge.svg' },
    { id: 63, name: 'Germany', code: '+49', svg: 'https://flagcdn.com/de.svg' },
    { id: 64, name: 'Ghana', code: '+233', svg: 'https://flagcdn.com/gh.svg' },
    { id: 65, name: 'Greece', code: '+30', svg: 'https://flagcdn.com/gr.svg' },
    { id: 66, name: 'Grenada', code: '+1-473', svg: 'https://flagcdn.com/gd.svg' },
    { id: 67, name: 'Guatemala', code: '+502', svg: 'https://flagcdn.com/gt.svg' },
    { id: 68, name: 'Guinea', code: '+224', svg: 'https://flagcdn.com/gn.svg' },
    { id: 69, name: 'Guinea-Bissau', code: '+245', svg: 'https://flagcdn.com/gw.svg' },
    { id: 70, name: 'Guyana', code: '+592', svg: 'https://flagcdn.com/gy.svg' },
    { id: 71, name: 'Haiti', code: '+509', svg: 'https://flagcdn.com/ht.svg' },
    { id: 72, name: 'Honduras', code: '+504', svg: 'https://flagcdn.com/hn.svg' },
    { id: 73, name: 'Hungary', code: '+36', svg: 'https://flagcdn.com/hu.svg' },
    { id: 74, name: 'Iceland', code: '+354', svg: 'https://flagcdn.com/is.svg' },
    { id: 75, name: 'India', code: '+91', svg: 'https://flagcdn.com/in.svg' },
    { id: 76, name: 'Indonesia', code: '+62', svg: 'https://flagcdn.com/id.svg' },
    { id: 77, name: 'Iran', code: '+98', svg: 'https://flagcdn.com/ir.svg' },
    { id: 78, name: 'Iraq', code: '+964', svg: 'https://flagcdn.com/iq.svg' },
    { id: 79, name: 'Ireland', code: '+353', svg: 'https://flagcdn.com/ie.svg' },
    { id: 80, name: 'Israel', code: '+972', svg: 'https://flagcdn.com/il.svg' },
    { id: 81, name: 'Italy', code: '+39', svg: 'https://flagcdn.com/it.svg' },
    { id: 82, name: 'Jamaica', code: '+1-876', svg: 'https://flagcdn.com/jm.svg' },
    { id: 83, name: 'Japan', code: '+81', svg: 'https://flagcdn.com/jp.svg' },
    { id: 84, name: 'Jordan', code: '+962', svg: 'https://flagcdn.com/jo.svg' },
    { id: 85, name: 'Kazakhstan', code: '+7', svg: 'https://flagcdn.com/kz.svg' },
    { id: 86, name: 'Kenya', code: '+254', svg: 'https://flagcdn.com/ke.svg' },
    { id: 87, name: 'Kiribati', code: '+686', svg: 'https://flagcdn.com/ki.svg' },
    { id: 88, name: 'Korea, North', code: '+850', svg: 'https://flagcdn.com/kp.svg' },
    { id: 89, name: 'Korea, South', code: '+82', svg: 'https://flagcdn.com/kr.svg' },
    { id: 90, name: 'Kuwait', code: '+965', svg: 'https://flagcdn.com/kw.svg' },
    { id: 91, name: 'Kyrgyzstan', code: '+996', svg: 'https://flagcdn.com/kg.svg' },
    { id: 92, name: 'Laos', code: '+856', svg: 'https://flagcdn.com/la.svg' },
    { id: 93, name: 'Latvia', code: '+371', svg: 'https://flagcdn.com/lv.svg' },
    { id: 94, name: 'Lebanon', code: '+961', svg: 'https://flagcdn.com/lb.svg' },
    { id: 95, name: 'Lesotho', code: '+266', svg: 'https://flagcdn.com/ls.svg' },
    { id: 96, name: 'Liberia', code: '+231', svg: 'https://flagcdn.com/lr.svg' },
    { id: 97, name: 'Libya', code: '+218', svg: 'https://flagcdn.com/ly.svg' },
    { id: 98, name: 'Liechtenstein', code: '+423', svg: 'https://flagcdn.com/li.svg' },
    { id: 99, name: 'Lithuania', code: '+370', svg: 'https://flagcdn.com/lt.svg' },
    { id: 100, name: 'Luxembourg', code: '+352', svg: 'https://flagcdn.com/lu.svg' },
    { id: 101, name: 'Madagascar', code: '+261', svg: 'https://flagcdn.com/mg.svg' },
    { id: 102, name: 'Malawi', code: '+265', svg: 'https://flagcdn.com/mw.svg' },
    { id: 103, name: 'Malaysia', code: '+60', svg: 'https://flagcdn.com/my.svg' },
    { id: 104, name: 'Maldives', code: '+960', svg: 'https://flagcdn.com/mv.svg' },
    { id: 105, name: 'Mali', code: '+223', svg: 'https://flagcdn.com/ml.svg' },
    { id: 106, name: 'Malta', code: '+356', svg: 'https://flagcdn.com/mt.svg' },
    { id: 107, name: 'Marshall Islands', code: '+692', svg: 'https://flagcdn.com/mh.svg' },
    { id: 108, name: 'Mauritania', code: '+222', svg: 'https://flagcdn.com/mr.svg' },
    { id: 109, name: 'Mauritius', code: '+230', svg: 'https://flagcdn.com/mu.svg' },
    { id: 110, name: 'Mexico', code: '+52', svg: 'https://flagcdn.com/mx.svg' },
    { id: 111, name: 'Micronesia', code: '+691', svg: 'https://flagcdn.com/fm.svg' },
    { id: 112, name: 'Moldova', code: '+373', svg: 'https://flagcdn.com/md.svg' },
    { id: 113, name: 'Monaco', code: '+377', svg: 'https://flagcdn.com/mc.svg' },
    { id: 114, name: 'Mongolia', code: '+976', svg: 'https://flagcdn.com/mn.svg' },
    { id: 115, name: 'Montenegro', code: '+382', svg: 'https://flagcdn.com/me.svg' },
    { id: 116, name: 'Morocco', code: '+212', svg: 'https://flagcdn.com/ma.svg' },
    { id: 117, name: 'Mozambique', code: '+258', svg: 'https://flagcdn.com/mz.svg' },
    { id: 118, name: 'Myanmar', code: '+95', svg: 'https://flagcdn.com/mm.svg' },
    { id: 119, name: 'Namibia', code: '+264', svg: 'https://flagcdn.com/na.svg' },
    { id: 120, name: 'Nauru', code: '+674', svg: 'https://flagcdn.com/nr.svg' },
    { id: 121, name: 'Nepal', code: '+977', svg: 'https://flagcdn.com/np.svg' },
    { id: 122, name: 'Netherlands', code: '+31', svg: 'https://flagcdn.com/nl.svg' },
    { id: 123, name: 'New Zealand', code: '+64', svg: 'https://flagcdn.com/nz.svg' },
    { id: 124, name: 'Nicaragua', code: '+505', svg: 'https://flagcdn.com/ni.svg' },
    { id: 125, name: 'Niger', code: '+227', svg: 'https://flagcdn.com/ne.svg' },
    { id: 126, name: 'Nigeria', code: '+234', svg: 'https://flagcdn.com/ng.svg' },
    { id: 127, name: 'North Macedonia', code: '+389', svg: 'https://flagcdn.com/mk.svg' },
    { id: 128, name: 'Norway', code: '+47', svg: 'https://flagcdn.com/no.svg' },
    { id: 129, name: 'Oman', code: '+968', svg: 'https://flagcdn.com/om.svg' },
    { id: 130, name: 'Pakistan', code: '+92', svg: 'https://flagcdn.com/pk.svg' },
    { id: 131, name: 'Palau', code: '+680', svg: 'https://flagcdn.com/pw.svg' },
    { id: 132, name: 'Palestine', code: '+970', svg: 'https://flagcdn.com/ps.svg' },
    { id: 133, name: 'Panama', code: '+507', svg: 'https://flagcdn.com/pa.svg' },
    { id: 134, name: 'Papua New Guinea', code: '+675', svg: 'https://flagcdn.com/pg.svg' },
    { id: 135, name: 'Paraguay', code: '+595', svg: 'https://flagcdn.com/py.svg' },
    { id: 136, name: 'Peru', code: '+51', svg: 'https://flagcdn.com/pe.svg' },
    { id: 137, name: 'Philippines', code: '+63', svg: 'https://flagcdn.com/ph.svg' },
    { id: 138, name: 'Poland', code: '+48', svg: 'https://flagcdn.com/pl.svg' },
    { id: 139, name: 'Portugal', code: '+351', svg: 'https://flagcdn.com/pt.svg' },
    { id: 140, name: 'Qatar', code: '+974', svg: 'https://flagcdn.com/qa.svg' },
    { id: 141, name: 'Romania', code: '+40', svg: 'https://flagcdn.com/ro.svg' },
    { id: 142, name: 'Russia', code: '+7', svg: 'https://flagcdn.com/ru.svg' },
    { id: 143, name: 'Rwanda', code: '+250', svg: 'https://flagcdn.com/rw.svg' },
    { id: 144, name: 'Saint Kitts and Nevis', code: '+1-869', svg: 'https://flagcdn.com/kn.svg' },
    { id: 145, name: 'Saint Lucia', code: '+1-758', svg: 'https://flagcdn.com/lc.svg' },
    { id: 146, name: 'Saint Vincent and the Grenadines', code: '+1-784', svg: 'https://flagcdn.com/vc.svg' },
    { id: 147, name: 'Samoa', code: '+685', svg: 'https://flagcdn.com/ws.svg' },
    { id: 148, name: 'San Marino', code: '+378', svg: 'https://flagcdn.com/sm.svg' },
    { id: 149, name: 'Sao Tome and Principe', code: '+239', svg: 'https://flagcdn.com/st.svg' },
    { id: 150, name: 'Saudi Arabia', code: '+966', svg: 'https://flagcdn.com/sa.svg' },
    { id: 151, name: 'Senegal', code: '+221', svg: 'https://flagcdn.com/sn.svg' },
    { id: 152, name: 'Serbia', code: '+381', svg: 'https://flagcdn.com/rs.svg' },
    { id: 153, name: 'Seychelles', code: '+248', svg: 'https://flagcdn.com/sc.svg' },
    { id: 154, name: 'Sierra Leone', code: '+232', svg: 'https://flagcdn.com/sl.svg' },
    { id: 155, name: 'Singapore', code: '+65', svg: 'https://flagcdn.com/sg.svg' },
    { id: 156, name: 'Slovakia', code: '+421', svg: 'https://flagcdn.com/sk.svg' },
    { id: 157, name: 'Slovenia', code: '+386', svg: 'https://flagcdn.com/si.svg' },
    { id: 158, name: 'Solomon Islands', code: '+677', svg: 'https://flagcdn.com/sb.svg' },
    { id: 159, name: 'Somalia', code: '+252', svg: 'https://flagcdn.com/so.svg' },
    { id: 160, name: 'South Africa', code: '+27', svg: 'https://flagcdn.com/za.svg' },
    { id: 161, name: 'South Sudan', code: '+211', svg: 'https://flagcdn.com/ss.svg' },
    { id: 162, name: 'Spain', code: '+34', svg: 'https://flagcdn.com/es.svg' },
    { id: 163, name: 'Sri Lanka', code: '+94', svg: 'https://flagcdn.com/lk.svg' },
    { id: 164, name: 'Sudan', code: '+249', svg: 'https://flagcdn.com/sd.svg' },
    { id: 165, name: 'Suriname', code: '+597', svg: 'https://flagcdn.com/sr.svg' },
    { id: 166, name: 'Sweden', code: '+46', svg: 'https://flagcdn.com/se.svg' },
    { id: 167, name: 'Switzerland', code: '+41', svg: 'https://flagcdn.com/ch.svg' },
    { id: 168, name: 'Syria', code: '+963', svg: 'https://flagcdn.com/sy.svg' },
    { id: 169, name: 'Taiwan', code: '+886', svg: 'https://flagcdn.com/tw.svg' },
    { id: 170, name: 'Tajikistan', code: '+992', svg: 'https://flagcdn.com/tj.svg' },
    { id: 171, name: 'Tanzania', code: '+255', svg: 'https://flagcdn.com/tz.svg' },
    { id: 172, name: 'Thailand', code: '+66', svg: 'https://flagcdn.com/th.svg' },
    { id: 173, name: 'Timor-Leste', code: '+670', svg: 'https://flagcdn.com/tl.svg' },
    { id: 174, name: 'Togo', code: '+228', svg: 'https://flagcdn.com/tg.svg' },
    { id: 175, name: 'Tonga', code: '+676', svg: 'https://flagcdn.com/to.svg' },
    { id: 176, name: 'Trinidad and Tobago', code: '+1-868', svg: 'https://flagcdn.com/tt.svg' },
    { id: 177, name: 'Tunisia', code: '+216', svg: 'https://flagcdn.com/tn.svg' },
    { id: 178, name: 'Turkey', code: '+90', svg: 'https://flagcdn.com/tr.svg' },
    { id: 179, name: 'Turkmenistan', code: '+993', svg: 'https://flagcdn.com/tm.svg' },
    { id: 180, name: 'Tuvalu', code: '+688', svg: 'https://flagcdn.com/tv.svg' },
    { id: 181, name: 'Uganda', code: '+256', svg: 'https://flagcdn.com/ug.svg' },
    { id: 182, name: 'Ukraine', code: '+380', svg: 'https://flagcdn.com/ua.svg' },
    { id: 183, name: 'United Arab Emirates', code: '+971', svg: 'https://flagcdn.com/ae.svg' },
    { id: 184, name: 'United Kingdom', code: '+44', svg: 'https://flagcdn.com/gb.svg' },
    { id: 185, name: 'United States', code: '+1', svg: 'https://flagcdn.com/us.svg' },
    { id: 186, name: 'Uruguay', code: '+598', svg: 'https://flagcdn.com/uy.svg' },
    { id: 187, name: 'Uzbekistan', code: '+998', svg: 'https://flagcdn.com/uz.svg' },
    { id: 188, name: 'Vanuatu', code: '+678', svg: 'https://flagcdn.com/vu.svg' },
    { id: 189, name: 'Vatican City', code: '+379', svg: 'https://flagcdn.com/va.svg' },
    { id: 190, name: 'Venezuela', code: '+58', svg: 'https://flagcdn.com/ve.svg' },
    { id: 191, name: 'Vietnam', code: '+84', svg: 'https://flagcdn.com/vn.svg' },
    { id: 192, name: 'Yemen', code: '+967', svg: 'https://flagcdn.com/ye.svg' },
    { id: 193, name: 'Zambia', code: '+260', svg: 'https://flagcdn.com/zm.svg' },
    { id: 194, name: 'Zimbabwe', code: '+263', svg: 'https://flagcdn.com/zw.svg' },
    { id: 195, name: 'HongKong', code: '+852', svg: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Flag_of_Hong_Kong.svg/2000px-Flag_of_Hong_Kong.svg.png' }
];
